### PR TITLE
Template app pages

### PR DESCRIPTION
**Pull request by br3ndonland**
The commits in this pull request will organize the application pages into templates.

Changes provided in these commits include:

- Move HTML to templates directory
- Organize HTML into templates
  - Use _layout.html_ for common header and footer
  - Update CDN links for latest versions of Bootstrap and DataTables
  - Use new API key from new gwgnewengland Google Cloud account
- Update CSS for map and templates
  - Set `main` height in CSS to nest map within `<main>` (issue #12)
  - Update CSS for new page layout.

This pull request addresses issues #12 and #37 .

The JavaScript will require refactoring to work with the new back-end API and page templates. I commented out most of the JavaScript files for now, and I will update the JavaScript from a separate branch.

### CODE REVIEW

**Comment by AbdouSeck** [comment]
Thank you so much for these changes. A `templates` directory, along with actual templates, was much needed.

At first glance, the following two issues were found:

1. Wrong function in template `layout.html`:
url_for('universities') wouldn't work because the view function name in `app.py` is `colleges`.
You should either change the function name in `app.py` or call `url_for('colleges')`.
This should have caused an `Internal Server Error` when the application is called. But I think, because of the server from previous runs/tests, you got a cached index page when you fired up the application. I recommend clearing the app's storage from your browser to make sure that you're not getting cached pages in return. You could also set the cache name in the javascript file to dynamically change every time you run the app. This will make sure that all previous caches are deleted (I think).

2. `static/js/index.js` is omitted (commented out):
This script is what installs and updates the service worker, so it needs to be added to the `layout.html` template. Most of the other javascript files can be omitted though.

I'll try and do a much more thorough check later today, once we've put our couch and bed back together. Talk to you soon!

**Comment by br3ndonland** [comment]
Thanks @AbdouSeck . Sorry I forgot to include my changes to _app.py_ in the last set of commits. This commit fixes the issue with the universities page. I also restored the Service Worker, and renamed the _index.js_ file to _sw-install.js_, so it's easier to keep track of what it does.

**Comment by AbdouSeck** [comment]
@br3ndonland, thanks for the changes. I'm happy to merge these changes but I wanted to make sure that I mentioned that once these changes make it to the `dev` branch, the app will no longer be static, and therefore will be impossible to host using GitHub Pages. The good thing about this is that GitHub Pages is still linked to the `master` branch, which has not yet received any of these changes. So, we'll still to be able to point people to the app until we decide to move changes from `dev` to `master`.

If we still are thinking about letting GitHub Pages host the site while the APIs are hosted elsewhere, we may have to do the templating a bit differently: basically still generate the static pages through templating, but nothing more. This means that we use view functions to generate the `index.html` and `universities.html` pages and then `add`, `commit` and `push` those `HTML` pages to GitHub.

If this is not clear, I am happy to discuss it further on Slack later this afternoon (preferably after 3 PM). Otherwise, we can meet next Saturday or Sunday to discuss this and the PDF file you shared with us on Slack. I'd really love to work on implementing those challenges!

Abdou

**Comment by AbdouSeck** [comment]
Also, the following static files are being cached in the server worker, but since most of them won't be needed anymore and some of them have their names changed, I recommend we stop caching them?
```
https://api-v3.mbta.com/stops
static/js/index.js
static/js/dbCaching.js
static/js/localforage.min.js
static/js/utilities.js
```
@br3ndonland, let me know what you think. If you would like to remove them from being cached, feel free to modify the server worker file (`sw.js`, I believe). The `staticScripts` variable should be edited as follows:

```
var staticScripts = [
  "https://code.jquery.com/jquery-3.2.1.slim.min.js",
  "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js",
  "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js",
  "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css",
  "https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css",
  "https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js",
  "https://cdn.datatables.net/responsive/2.2.1/css/responsive.dataTables.min.css",
  "https://cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js",
  "data/cleaner_universities.json",
  "index.html",
  "static/js/sw-install.js",
];
```

This should actually reduce the storage footprint of the app.

Abdou

**Comment by br3ndonland** [comment]
Thanks for your comments @AbdouSeck.

- **JavaScript**
  - I pushed your recommended changes to the Service Worker. The commit updates the list of cached files, and also updates the API key for our new Google account.
  - I will continue to refactor and update the Service Worker and other JavaScript files. For example, the map JavaScript will need to be updated to generate markers from our API instead of the data fetched directly from the MBTA API. I will do this from a separate branch.
- **GitHub Pages**
  - GitHub Pages builds from the `master` or `gh-pages` branches. We can safely make changes on the `dev` branch, but once we merge to `master`, the static site would no longer work.
  - To protect the static site in case we push to `master`, I created a `gh-pages` branch off of `master`, and switched the GitHub Pages build to the `gh-pages` branch. We can maintain the static site there.
- **Flask, deployment and hosting**
  - You're correct that we won't be able to host the Flask app as a static site anymore. I think we should deploy with full Flask functionality, rather than generating static pages offline.
  - I'm happy to take on the deployment. I think it should be the last thing we do, after we have a functioning app with all the planned features.
  - If we deploy onto Google Cloud Kubernetes Engine, I think we can just point our mbtaccess.org domain name there.
  - If we need another option, I would suggest Netlify. It's mostly used for static sites, but they do have some instructions for Python, and people rave about the great user experience. We can configure Netlify to build from our GitHub repo, and point our mbtaccess.org domain name there.
  - If Netlify doesn't work, we can manually configure an Apache or Nginx server and clone the app repo onto the server. I have done this before on DigitalOcean.

**This week, I'm hoping to refactor all the JavaScript, and get a single Docker container running for the application.** A meeting next weekend would be great.

**Comment by AbdouSeck** [comment]
Oh never mind. I was able to add the localhost server URL's and everything seems fine now. I get the following warning from Chrome:
```
Resource interpreted as Stylesheet but transferred with MIME type application/javascript: "https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js".
```

I am not particularly sure what it's talking about here, but it seems to affect the `/universities` endpoint fairly severely.
The following is what the universities table now looks like:

screen shot 2018-07-22 at 20 04 42

Any idea why this is happening?

I also failed to mention that the `layout.html` page contains the `script` tag that's importing the Maps API when this is only needed for the `index` page. Maybe the Maps API code should only be in the `index.html` template. In fact, if you look at your console when you're on the `universities` page, it shows a fair bit of `Javascript` errors below the `dataTable.js` warning. Could you also please take a look at those errors?

**Comment by br3ndonland** [comment]
Thanks for your patience on these issues @AbdouSeck, and for checking out the code so thoroughly. Your comments have cleaned up my commits and really improved the app. Going forward, I would suggest we keep this PR focused on templating and deal with the DataTables quirks, and any additional JavaScript changes, in a separate PR.

- **Templates**
  - I substantially improved the templating today.
  - I previously had most of the HTML in *layout.html*, with only the `{% block content %}` in the middle being different for each page.
  - I revised *layout.html* to be a concise master layout for the pages, and added more templates for other parts of the page.
  - **Templating scripts**:
    - I agree that we should only load scripts when they are needed on the page. We should load the maps JavaScript only on the map page, and the universities JavaScript only on the universities page.
    - To accomplish this, I divided the script tags into those common to all pages, and those unique to a specific page.
    - The common scripts are stored in *scripts.html* and loaded with each template using `{% include 'scripts.html' %}` in *layout.html*.
    - The scripts unique to each page are stored in the HTML for the page (*index.html* or *universities.html*) inside `{% block script %}`. The script block is then called in *layout.html*.
- **DataTables**
  - The DataTables have started running over the footer on both pages. **It started after I set a height for `main` in the CSS.**

    screenshot_2018-07-17-mbtaccess-datatables

  - I thought it might be ignoring the Flask-templated footer, but I have gotten the same error on the static site without templating.
  - Upon inspection by dev tools, DataTables seems to be applying a `no-footer` class.
  - I applied some CSS to the universities DataTable in a prior commit so it fits above the footer until we figure out the issue. This is why it looks smaller right now.

**Comment by AbdouSeck** [comment]
Hi @br3ndonland,

I think I found what your issue with `DataTables` is:
```
 <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js">
```
This link is inside `universities.html`, but a `link` tag should receive a CSS file or something else. Not a javascript file. Maybe changing the `href` attribute to the actual `CSS` file would fix the table issues.

Also, you remove the `index.html` endpoint from `app.py`, but are still trying to cache `index.html` inside the `sw.js` file. This causes an error. You can remove the `"index.html"` element from the `staticScripts` variable inside `sw.js` to avoid this error. Or, you could change the value from `"index.html"` or `"index"`.

It never hurts to have endpoints that end with `.html` since it's just a page being served. However, if they cause confusions, then I am definitely for removing them.

Finally, I recommend emptying the browser cache every time you test a page. Sometimes cached pages can make it seem like there are no errors or warnings.

I am heading home, but I'll be adding unit tests for both `app.py` and `utilities.py` within the next hour or so. I will make sure I don't touch any files you've already been working on.

Finally, sorry about this long back-and-forth. I am just trying to avoid merging a pull request that may introduce console errors/warnings. Not trying to be too anal.

**Comment by AbdouSeck** [comment]
@br3ndonland I just noticed that you changed the versions for `DataTable.js`. Now, it looks like the templating `branch` is using version `1.10.19` while all the other branches are on version `1.10.16`. Is it possible for that to be part of the reason that table layouts have changed?

**Comment by AbdouSeck** [comment]
@br3ndonland thanks for the changes. But most of all, thanks for indulging my annoyances. I am going to submit a pull request with `unit tests` and [`travis CI`](https://travis-ci.org/) hooks. The latter should trigger test runs every time we push commits to GitHub.

**Comment by br3ndonland** [comment]
Great, thanks @AbdouSeck! I do appreciate your comments in this thread, and I think testing with CI is a great idea.

**Pull request merged**
