### PR TITLE
Add unit tests for app.py and utilities.py

### PR DESCRIPTION
**Pull request by AbdouSeck**
This pull request includes 2 things:

1. Unit tests inside the `tests` directory to tests functions in `app.py` and `utilities.py`
2. Travis CI hook to trigger test runs when commits are pushed to GitHub.

The test run status image is also added to the `README.md` file to indicate whether or not the latest test runs passed.

Please let me know if something looks amiss.

Thanks,

Abdou

### CODE REVIEW

**Comment by br3ndonland** [comment]
@AbdouSeck thanks for this helpful and focused PR. Allow me some time to work with the unit tests. A few questions from my work today:

- Do we need both Python 3.5 and 3.6 specified in *travis.yml*? Will this include future Python versions also? I'm running Python 3.7.0 locally.
- Why did the first two Travis CI checks fail? Based on the [Travis CI build history](https://travis-ci.org/growwithgooglema/mbtaccess/builds), it looks like there was a typo, plus some issues with Python versions? In the future, it would be helpful for you to add this information to your Git commit messages.
- Did you also configure [Unit testing Python in VS Code](https://code.visualstudio.com/docs/python/unit-testing)? If so, what settings did you use?
- Just to clarify, by "test run status image" you mean test badge? It can be added to *README.md*, but hasn't been yet, right?

I think we should clarify our Git practices also. Git is always an involved and sensitive topic, so we can save it for our next meetup if you want. Specifically:

- I would prefer to have a separate `testing` branch, from the current `dev`. We're just adding merge commits by using the old `flaskifying` branch.
- If we use `flaskifying` for adding tests, are you okay with me committing directly to `flaskifying`? Should I branch off `flaskifying` and submit a pull request? Should I just recommend changes here and have you make all the commits?
- As I mentioned above, providing some more detail in Git commit messages when needed will help collaborators understand the changes made.

**Comment by AbdouSeck** [comment]
Hi @br3ndonland,
I am in Minneapolis for work until Friday, so I may not respond as quickly as I'd want. But I am going to get right to it:

- I chose both 3.5 and 3.6 because they happen to be very stable versions of python 3. I did have 3.7 on there, but travis-ci.org has not yet added support for 3.7. Or at least, it doesn't work well yet. I, myself, brewed a fresh copy of python 3.7 not long ago and have been using it. All the unit tests should be run (whether or not they passed will depend on the code in your branch). Finally, as soon as travis supports python 3.7 fully, we should add the version on there. I just removed it because it doesn't work properly on their systems. But I can report that the tests are passing on my end, and I use 3.7.

- Yes, the first 2 builds failed (kind of on purpose) for the `flaskifying` branch because I wanted to see how travis would communicate the errors to me. I just had a few things omitted from the code that would trigger errors. I also knew that support for python 3.7 wasn't there, but wanted to see the output myself. As long as the build for the pull request is `passing`, then I would not worry about previous builds. What would worry me is having failing builds right after a successful one.
Also, `GitHub` does provide side-by-side `diff` information between a commit and its immediate child commit. So, that's a pretty decent way of checking what happened between a failed build and a successful one. In any case, I can use much better discipline when writing commit messages though. So, I will keep that in mind.

- I did not configure unit tests for VS Code at all. In fact, I did not even know that was possible. Thanks for sharing that link, by the way. It looks like that could make things much easier than having to type the commands on the shell. I just call the following every time I add new code that could affect the unit tests:
```
# Need to be inside your virtual environment
python -W ignore -m unittest discover -vv -s tests -p "*test.py"
```
This calls python with the following twists:
`-W ignore`: Tells the python interpreter to ignore `warnings` since those are written to the standard error and can act like errors, when they're usually deprecating warnings.
`-m unittest`: Tells the python interpreter to import the `unittest` module
`discover -vv -s tests -p "*test.py"`: Tells the `unittest` module to discover and run test cases (with a verbosity level of 2) located inside the directory `tests` inside python files with the pattern `"*test.py"`

That's all that's needed to run the test cases. I am sure configuring that for VS Code wouldn't be too hard.


- Yes, by *"test run status image"*, I mean the badge thingy you see often in the `README.md` file of repos.

- I am not sure it's good practice at all to have a separate branch for unit testing. Unit tests are supposed to be baked into every branch, since eventually every branch needs to be merged to a production or dev branch. It is by passing the test cases that one knows that the introduced code won't break what's already been working. If you mean that we should have a `testing` branch for testing our deployment processes, then I think that's a good idea. But I also don't think we need that if we've got the `dev` branch already. In my very limited experience, having a `testing` branch just means that you've got a testing stage in your deployment process (like QA and what not). Is that what you're referring to?

- I don't think it matters who adds test cases, as long as they don't cause conflicts when it comes time to merging. And having two people work from the same branch could wreak quite the havoc. The good thing is you can write tests in your own branch without needing to touch the `flaskifying` branch. However, If there are edits you would like me to make before you merge this pull request, please feel free to share them here and I will jump right on making them when I am done with my meetings today. Otherwise, if you wish to test "uncovered" functions in the current code or wish to start a whole new test file, you can definitely do that in your chosen branch.

- **Final note**: If this pull request gets merged to the `dev` branch and all our oersonal branches, every subsequent push or merge should trigger test runs on travis. We can limit the triggers to only happen with pull requests though. The idea is that as long as a branch has the `.travis.yml`, its pushes and pull requests are tested. This allows the person doing the eventual merging to be safe in assuming that the new code is not going to break any existing functionalities, unless the existing test cases have been modified. In which case, a slightly more thorough review is needed.

I hope some of that makes sense. Otherwise, I am happy to add more clarifications.

Thanks for the questions and comments!

**Comment by br3ndonland** [comment]
Thanks for the clarifications @AbdouSeck.

- **Testing**: I did check out your Git diffs but was still unsure of what was going on. This is why I recommended more detailed commit messages. Thanks for explaining it. I'm going to start working with [Unit testing Python in VS Code](https://code.visualstudio.com/docs/python/unit-testing), and I'll let you know how it goes.
- **Git**: Sorry for the confusing name suggestion for the testing branch. I just meant we should make a new feature branch from `dev` for writing the tests. I agree we should *run* tests on every branch, but I think we should *write* tests on a separate branch. Once we have tests in place, yes, we should implement tests through Travis CI on each branch. I still think we should make a new branch instead of re-using the `flaskifying` branch. Feature branches (branches off `master` or `dev`) should be deleted after they are merged, in my opinion. This would be considered Git Flow style. See the Git Flow pages from [Atlassian](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) and [Vincent Driessen](https://nvie.com/posts/a-successful-git-branching-model/) for more info. We can discuss this further, and maybe revise our contributing guidelines once we arrive at a consensus.

**Comment by AbdouSeck** [comment]
Good morning @br3ndonland.

I am definitely fine with deleting feature branches that are no longer needed. I see the `flaskifying` branch as a still ongoing implementation kind of branch (endpoints, utilities and their tests). So, my understanding was that as long as I am working on those tasks that all have to do with moving in the Flask direction, then I was okay to use the same branch. I don't mind changing my not-so-good habits for good ones though.
I am happy to embrace whatever flow makes us more productive and keeps us from introducing bugs to destination branches. If it helps to delete merged branches, I am more than happy to do that.
This also will mean that I won't submit pull requests until I am certain that all the intended features and tests have been written, which sounds like how it should actually be.

Thanks for the links!

**Pull request closed without merging**
